# Generated by Django 3.2.3 on 2021-05-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=50)),
                ('identification', models.CharField(max_length=10)),
            ],
        ),
    ]
