# Generated by Django 3.2.3 on 2021-05-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=35)),
                ('father_name', models.CharField(max_length=35)),
                ('date_of_birth', models.DateTimeField()),
                ('sex', models.CharField(max_length=30)),
                ('married', models.CharField(max_length=30)),
                ('cnic', models.CharField(blank=True, max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('addres', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=30)),
                ('phone_no_2', models.CharField(max_length=30)),
                ('landline', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishfarm.employeebasicinfo')),
            ],
        ),
    ]
