# Generated by Django 3.2.3 on 2021-05-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0002_employeebasicinfo_employeecontactdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishfarm.employeebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('years', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishfarm.employeebasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('addres', models.CharField(max_length=100)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishfarm.customer')),
            ],
        ),
    ]
