# Generated by Django 3.2.3 on 2021-06-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0004_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Person_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
