# Generated by Django 3.2.3 on 2021-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0005_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='Person_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
