# Generated by Django 3.2.3 on 2021-06-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0008_auto_20210605_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='log_in',
        ),
    ]
