# Generated by Django 3.2.3 on 2021-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0011_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('page_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
