# Generated by Django 3.2.3 on 2021-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0013_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info', models.CharField(max_length=200)),
                ('detail_info', models.CharField(max_length=500)),
            ],
        ),
    ]
