# Generated by Django 3.2.3 on 2021-06-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0015_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
