# Generated by Django 3.2.3 on 2021-06-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0017_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercontact',
            name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='Customer_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerContact',
        ),
    ]
