# Generated by Django 3.2.3 on 2021-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0019_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('Name_Costomer', models.CharField(max_length=255, null=True)),
                ('GrandTotal', models.DecimalField(decimal_places=3, default='0.00', max_digits=8, null=True)),
            ],
        ),
    ]
