# Generated by Django 3.2.3 on 2021-06-30 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fishfarm', '0020_req_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdereProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('CustomerID', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishfarm.req_info')),
            ],
        ),
    ]
