# Generated by Django 3.2.3 on 2021-07-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0025_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='profile_pic',
            field=models.ImageField(blank=True, default='download (1).png', null=True, upload_to=''),
        ),
    ]
